//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageTool
    {
        public int LanguageToolId { get; set; }
        public int ToolId { get; set; }
        public int LanguagePageId { get; set; }
        public string LanguageToolValue { get; set; }
    
        public virtual LanguagePage LanguagePage { get; set; }
        public virtual PageTool PageTool { get; set; }
    }
}
