//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageTool
    {
        public PageTool()
        {
            this.LanguageTools = new HashSet<LanguageTool>();
        }
    
        public int ToolId { get; set; }
        public string ToolName { get; set; }
        public int PageId { get; set; }
    
        public virtual ICollection<LanguageTool> LanguageTools { get; set; }
        public virtual SysPage SysPage { get; set; }
    }
}
