//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeoManager
    {
        public int Id { get; set; }
        public int ToolId { get; set; }
        public int LanguagePageId { get; set; }
        public string SeoUrl { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string UrlParameter { get; set; }
    
        public virtual SeoPageTool SeoPageTool { get; set; }
    }
}
