//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeoPageTool
    {
        public SeoPageTool()
        {
            this.SeoLanguageTools = new HashSet<SeoLanguageTool>();
            this.SeoManagers = new HashSet<SeoManager>();
        }
    
        public int ToolId { get; set; }
        public string ToolName { get; set; }
        public int PageId { get; set; }
        public string PageUrl { get; set; }
    
        public virtual ICollection<SeoLanguageTool> SeoLanguageTools { get; set; }
        public virtual ICollection<SeoManager> SeoManagers { get; set; }
        public virtual SysPage SysPage { get; set; }
    }
}
